### ISSUE TITLE
Is it possible to use whereIntegerInRaw

### ISSUE THREAD

**Issue by emad-sure** [biiiiiigmonster/hasin#4]
Hey after doing some search around i found according to this article that the performance of whereIntegerInRaw is way better than whereIn so is it possible to use in hasin package ? 

check the article. 
https://www.yellowduck.be/posts/optimising-large-wherein-queries-in-laravel/

**Comment by biiiiiigmonster** [comment]
Thanks for your advice.

But there may be some misunderstandings, actually, `hasin` implemented it according to `has`, in the form of subquery, such as `select * from users where users.id in (select posts.user_id from posts)`

`whereIntegerInRaw`'s param need `array` or `Arrayable`, it doesn't apply here.
