### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rebbieboi** [biiiiiigmonster/hasin#5]
since this is using whereIn, will this be affected by the too many placeholders problem? i.e https://stackoverflow.com/questions/53554260/eloquent-wherein-error1390-prepared-statement-contains-too-many-placeholders-la

**Comment by biiiiiigmonster** [comment]
Thx !
there will be no such problem.
accurately, `whereHasIn` is used subQuery(`where xxx in (subQuery)`) way, like `where exist (subQuery)`, there is no parameter binding during.

**Comment by rebbieboi** [comment]
thank you!
